# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: my.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'my.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08my.proto\x12\ntommy.game\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x08\x12.\n\nlast_login\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x63ur_ad\x18\x05 \x01(\t\x12)\n\x06status\x18\x06 \x01(\x0e\x32\x19.tommy.game.Player.Status\x12$\n\x07\x61\x64\x64ress\x18\x07 \x01(\x0b\x32\x13.tommy.game.Address\"*\n\x06Status\x12\x07\n\x03NEW\x10\x00\x12\r\n\tCONFIRMED\x10\x01\x12\x08\n\x04\x44IED\x10\x02\"\'\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYER']._serialized_start=58
  _globals['_PLAYER']._serialized_end=300
  _globals['_PLAYER_STATUS']._serialized_start=258
  _globals['_PLAYER_STATUS']._serialized_end=300
  _globals['_ADDRESS']._serialized_start=302
  _globals['_ADDRESS']._serialized_end=341
# @@protoc_insertion_point(module_scope)
