# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: groom.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'groom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgroom.proto\x12\x05groom\",\n\x17RoomRegistrationRequest\x12\x11\n\troom_name\x18\x01 \x01(\t\"+\n\x18RoomRegistrationResponse\x12\x0f\n\x07room_id\x18\x01 \x01(\t\"$\n\x0fGetGroomRequest\x12\x11\n\troom_name\x18\x01 \x01(\t\"%\n\x10GetGroomResponse\x12\x11\n\troom_name\x18\x01 \x01(\t2\x9f\x01\n\x05Groom\x12Q\n\x0eRegisterToRoom\x12\x1e.groom.RoomRegistrationRequest\x1a\x1f.groom.RoomRegistrationResponse\x12\x43\n\x08GetGroom\x12\x1e.groom.RoomRegistrationRequest\x1a\x17.groom.GetGroomResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOMREGISTRATIONREQUEST']._serialized_start=22
  _globals['_ROOMREGISTRATIONREQUEST']._serialized_end=66
  _globals['_ROOMREGISTRATIONRESPONSE']._serialized_start=68
  _globals['_ROOMREGISTRATIONRESPONSE']._serialized_end=111
  _globals['_GETGROOMREQUEST']._serialized_start=113
  _globals['_GETGROOMREQUEST']._serialized_end=149
  _globals['_GETGROOMRESPONSE']._serialized_start=151
  _globals['_GETGROOMRESPONSE']._serialized_end=188
  _globals['_GROOM']._serialized_start=191
  _globals['_GROOM']._serialized_end=350
# @@protoc_insertion_point(module_scope)
