# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import groom_pb2 as groom__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in groom_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GroomStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterToRoom = channel.unary_unary(
                '/groom.Groom/RegisterToRoom',
                request_serializer=groom__pb2.RoomRegistrationRequest.SerializeToString,
                response_deserializer=groom__pb2.RoomRegistrationResponse.FromString,
                _registered_method=True)
        self.GetGroom = channel.unary_unary(
                '/groom.Groom/GetGroom',
                request_serializer=groom__pb2.RoomRegistrationRequest.SerializeToString,
                response_deserializer=groom__pb2.GetGroomResponse.FromString,
                _registered_method=True)


class GroomServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterToRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroomServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterToRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterToRoom,
                    request_deserializer=groom__pb2.RoomRegistrationRequest.FromString,
                    response_serializer=groom__pb2.RoomRegistrationResponse.SerializeToString,
            ),
            'GetGroom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroom,
                    request_deserializer=groom__pb2.RoomRegistrationRequest.FromString,
                    response_serializer=groom__pb2.GetGroomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'groom.Groom', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('groom.Groom', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Groom(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterToRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groom.Groom/RegisterToRoom',
            groom__pb2.RoomRegistrationRequest.SerializeToString,
            groom__pb2.RoomRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groom.Groom/GetGroom',
            groom__pb2.RoomRegistrationRequest.SerializeToString,
            groom__pb2.GetGroomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
