# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: groom.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'groom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgroom.proto\x12\x05groom\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\",\n\x17RoomRegistrationRequest\x12\x11\n\troom_name\x18\x01 \x01(\t\"+\n\x18RoomRegistrationResponse\x12\x0f\n\x07room_id\x18\x01 \x01(\t\"M\n\tNewsFlash\x12-\n\tnews_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tnews_item\x18\x02 \x01(\t\"#\n\x10NewsStreamStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\"_\n\x0fReceivedMessage\x12,\n\x08msg_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x63ontents\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t2\xdf\x01\n\x05Groom\x12Q\n\x0eRegisterToRoom\x12\x1e.groom.RoomRegistrationRequest\x1a\x1f.groom.RoomRegistrationResponse\x12<\n\rSendNewsFlash\x12\x10.groom.NewsFlash\x1a\x17.groom.NewsStreamStatus(\x01\x12\x45\n\x0fStartMonitoring\x12\x16.google.protobuf.Empty\x1a\x16.groom.ReceivedMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOMREGISTRATIONREQUEST']._serialized_start=84
  _globals['_ROOMREGISTRATIONREQUEST']._serialized_end=128
  _globals['_ROOMREGISTRATIONRESPONSE']._serialized_start=130
  _globals['_ROOMREGISTRATIONRESPONSE']._serialized_end=173
  _globals['_NEWSFLASH']._serialized_start=175
  _globals['_NEWSFLASH']._serialized_end=252
  _globals['_NEWSSTREAMSTATUS']._serialized_start=254
  _globals['_NEWSSTREAMSTATUS']._serialized_end=289
  _globals['_RECEIVEDMESSAGE']._serialized_start=291
  _globals['_RECEIVEDMESSAGE']._serialized_end=386
  _globals['_GROOM']._serialized_start=389
  _globals['_GROOM']._serialized_end=612
# @@protoc_insertion_point(module_scope)
