# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08my.proto\x12\ntommy.game\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x03\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x08\x12\x30\n\nlast_login\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x12\x14\n\nlogin_time\x18\t \x01(\x05H\x00\x12\x0e\n\x06\x63ur_ad\x18\x05 \x01(\t\x12)\n\x06status\x18\x06 \x01(\x0e\x32\x19.tommy.game.Player.Status\x12$\n\x07\x61\x64\x64ress\x18\x07 \x01(\x0b\x32\x13.tommy.game.Address\x12\x16\n\x0eprevious_games\x18\x08 \x03(\t\x12\x34\n\tinventory\x18\n \x03(\x0b\x32!.tommy.game.Player.InventoryEntry\x1a\x30\n\x0eInventoryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"*\n\x06Status\x12\x07\n\x03NEW\x10\x00\x12\r\n\tCONFIRMED\x10\x01\x12\x08\n\x04\x44IED\x10\x02\x42\x11\n\x0flast_login_data\"\'\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYER_INVENTORYENTRY._options = None
  _PLAYER_INVENTORYENTRY._serialized_options = b'8\001'
  _PLAYER._serialized_start=58
  _PLAYER._serialized_end=471
  _PLAYER_INVENTORYENTRY._serialized_start=360
  _PLAYER_INVENTORYENTRY._serialized_end=408
  _PLAYER_STATUS._serialized_start=410
  _PLAYER_STATUS._serialized_end=452
  _ADDRESS._serialized_start=473
  _ADDRESS._serialized_end=512
# @@protoc_insertion_point(module_scope)
